# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'PokerCircles' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokerCircles

  target 'PokerCirclesTests' do
    inherit! :search_paths
    # Add the Firebase pods
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  
  # (Optional) If you want Firebase Analytics
  pod 'Firebase/Analytics'
  end

  target 'PokerCirclesUITests' do
    # Pods for testing
  end

end
